name: Our Steps
on: push
jobs:
  zeroone:
    runs-on: ubuntu-latest
    steps:
      - id: gen-num
        run: echo "num=$(($RANDOM % 2))" >> "$GITHUB_OUTPUT"
      - if: steps.gen-num.outputs.num == 0
        run: echo zero
      - if: steps.gen-num.outputs.num == 1
        run: echo one